---
deployment:
      tasks:
        - export DEPLOYPATH=/home/fgwsxsyn/subdomains/qr-undangan  # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
